"""
Generate a personalized speculative job application letter via LLM.

Three tiers based on available contact data:
  full     — has name + company + title
  partial  — has name + company only
  generic  — missing name, fallback to company team or hiring manager
"""

import re
import threading
import requests

from pipeline.llm_client import llm_generate, LLM_BACKEND


def _looks_like_name(s: str) -> bool:
    s = s.strip()
    if not s or len(s) < 2 or len(s) > 30:
        return False
    if not s[0].isalpha():
        return False
    if any(c.isdigit() for c in s):
        return False
    if re.search(r'[.,;:!?@#$%^&*()_+=\[\]{}<>]', s):
        return False
    return True


def _looks_like_company(s: str) -> bool:
    s = s.strip()
    if not s or len(s) < 2:
        return False
    if re.match(r'^[\w\-]+\.(com|io|ai|de|fr|nl|tech|co|app|net|org|uk|eu)$', s, re.I):
        return False
    return True


def _looks_like_title(s: str) -> bool:
    s = s.strip()
    if not s or len(s) > 80:
        return False
    if " at " in s.lower():
        return False
    return True


def _domain_to_display(domain: str) -> str:
    parts = domain.lower().split(".")
    if parts[0] in ("www", "app", "mail", "api", "dev"):
        parts = parts[1:]
    return parts[0].replace("-", " ").replace("_", " ").title() if parts else domain


def _assess(contact: dict) -> dict:
    first   = (contact.get("first_name") or "").strip()
    last    = (contact.get("last_name")  or "").strip()
    company = (contact.get("company")    or "").strip()
    domain  = (contact.get("company_domain") or "").strip()
    title   = (contact.get("title")     or "").strip()

    good_first   = _looks_like_name(first)
    good_company = _looks_like_company(company)
    good_title   = _looks_like_title(title)

    display_company = company if good_company else (_domain_to_display(domain) if domain else "")

    if good_first and good_company and good_title:
        tier = "full"
    elif good_first and display_company:
        tier = "partial"
    else:
        tier = "generic"

    return {
        "tier":    tier,
        "first":   first if good_first else "",
        "last":    last,
        "company": display_company,
        "domain":  domain,
        "title":   title if good_title else "",
    }


_blurb_cache: dict[str, str] = {}
_blurb_lock  = threading.Lock()


def _company_blurb(company: str, domain: str) -> str:
    key = domain or company
    if not key:
        return ""
    with _blurb_lock:
        if key in _blurb_cache:
            return _blurb_cache[key]
    # HTTP request outside the lock so workers don't block each other
    query  = company or domain
    result = ""
    try:
        r = requests.get(
            "https://api.duckduckgo.com/",
            params={"q": query, "format": "json",
                    "no_redirect": "1", "no_html": "1", "skip_disambig": "1"},
            timeout=3,
        )
        abstract = r.json().get("AbstractText", "").strip()
        if abstract:
            result = abstract[:300]
    except Exception:
        pass
    with _blurb_lock:
        _blurb_cache[key] = result
    return result


SIGNATURE = (
    "Best regards,\n\n"
    "Akrem ALAMINE\n"
    "+216 93 510 084\n"
    "linkedin.com/in/akrem-alamine\n"
    "akrem.alamine@gmail.com"
)

# Closing phrases the LLM may produce — everything from here onward gets replaced
_CLOSING_PATTERNS = re.compile(
    r'\n\s*(best regards|kind regards|regards|sincerely|yours sincerely|'
    r'warm regards|yours faithfully|cheers|thank you[,.]?)[\s\S]*$',
    re.IGNORECASE,
)

# Fixed body paragraphs — never generated by LLM, never wrong
_FIXED_INTRO = (
    "I am writing to express my interest in a DevOps or cloud infrastructure role at {company}. "
    "With hands-on experience in CI/CD pipelines, infrastructure automation, and cloud deployment, "
    "I am confident I can contribute to your engineering team from day one."
)

_FIXED_CV = (
    "My most recent experience was an HPC systems internship at Q-Leap Networks GmbH (Germany), "
    "where I built and automated a full production cluster: Slurm workload manager, OpenLDAP, "
    "NFS storage, Spack package management, and a Prometheus/Grafana monitoring stack. "
    "Before that, at RIF Group I provisioned OpenStack private cloud infrastructure using Ansible "
    "and built Docker-based CI/CD pipelines that automated the full build-test-deploy cycle. "
    "I am comfortable working across the stack, from bare-metal provisioning and IaC to "
    "container orchestration and observability. "
    "I have attached my CV and would welcome a brief conversation if there is a suitable opening."
)


def _prompt_snippet(company: str, blurb: str) -> str:
    """Ask the LLM for ONE short paragraph — why this company specifically, from a DevOps angle."""
    context = f"About {company}: {blurb}\n\n" if blurb else ""
    return (
        f"{context}Write 1-2 sentences (maximum 40 words) explaining what specifically attracts "
        f"a DevOps/cloud infrastructure engineer to {company}. "
        f"Focus on their infrastructure, deployment practices, cloud stack, or engineering culture "
        f"— not generic praise. Be concrete. "
        f"Do NOT start with 'I', do NOT use bullet points, do NOT include a greeting or closing. "
        f"Output only those 1-2 sentences, nothing else."
    )


def _assemble(greeting: str, company: str, snippet: str) -> str:
    intro  = _FIXED_INTRO.format(company=company)
    # Clean up snippet — strip accidental greetings/closings the LLM might sneak in
    snippet = re.sub(r'^(dear\s+\S+[,.]?\s*)', '', snippet.strip(), flags=re.I)
    snippet = _CLOSING_PATTERNS.sub('', snippet).strip()
    return f"{greeting}\n\n{intro}\n\n{snippet}\n\n{_FIXED_CV}\n\n{SIGNATURE}"


def apply_signature(text: str) -> str:
    """Strip any LLM-generated closing and append the standard SIGNATURE."""
    stripped = _CLOSING_PATTERNS.sub('', text).rstrip()
    return f"{stripped}\n\n{SIGNATURE}"


def generate_letter(contact: dict, cv: dict, llm_fn=None) -> str:
    """Generate a letter using a fixed template — LLM fills only the company interest snippet."""
    q     = _assess(contact)
    blurb = _company_blurb(q["company"], q["domain"])

    # Greeting
    if q["first"]:
        greeting = f"Dear {q['first']},"
    elif q["company"]:
        greeting = f"Dear {q['company']} team,"
    else:
        greeting = "Dear Hiring Manager,"

    company = q["company"] or "your company"

    # LLM generates only the interest snippet
    prompt = _prompt_snippet(company, blurb)
    call   = llm_fn if llm_fn is not None else llm_generate
    snippet = call(prompt, max_tokens=80, temperature=0.4)

    if not snippet or len(snippet.strip()) < 10:
        snippet = f"{company}'s focus on scalable infrastructure and engineering quality makes it exactly the kind of environment where I want to grow my DevOps and cloud skills."

    return _assemble(greeting, company, snippet)


def letter_tier(contact: dict) -> str:
    return _assess(contact)["tier"]
